server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/t1?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true